name: shyft_doc
channels:
  - shyft-os
  - main
  - conda-forge
  - bokeh
  - defaults
dependencies:
  - shyft=4.25.88
  - pydot
  - netcdf4
  - coverage
  - twine
  - sphinx_rtd_theme
  - sphinx
  - pytest
  - sphinx-autodoc-typehints
  - pyproj
  - matplotlib
  - pip
  - pytest-cov
  - pyyaml
  - shapely
  - pillow
  - pint
  - lxml
  - anaconda-client
  - bokeh
  - requests
  - numpy[version='>1.20']
  - pyside2[version='>=5.13.2']
  - python=3.9
  - sphinxcontrib-htmlhelp
  - recommonmark
  - sphinxcontrib
  - nbsphinx
  - ipython
  - jupyter
